version: "2"
services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ftp-app-data:/home/username/
      - ftp-conf-files:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: "$strTraefikDomains"
      FTP_USER_NAME: $username
      FTP_USER_PASS: $mypass
      FTP_USER_HOME: /home/username
    restart: always
    labels:
      io.rancher.container.hostname_override: container_name
      traefik.enable: true
      traefik.port: 21
      traefik.backend.loadbalancer.stickiness: true
      traefik.backend.loadbalancer.method: drr
      traefik.backend.buffering.retryExpression: IsNetworkError() && Attempts() < 5
      traefik.frontend.rule: Host:$strTraefikDomains
      io.rancher.scheduler.affinity:host_label: ${host_label}
volumes:
  ftp-app-data:
    external: true
    driver: rancher-nfs
  ftp-conf-files:
    external: true
    driver: rancher-nfs
