version: "2"
volumes:
  ftp-app-data:
    external: true
    driver: rancher-nfs
  ftp-conf-files:
    external: true
    driver: rancher-nfs
services:
  ftpd-server:
    image: stilliard/pure-ftpd
    ports:
      - 30021:21
      - 30000:30000
      - 30001:30001
      - 30002:30002
      - 30003:30003
      - 30004:30004
      - 30005:30005
      - 30006:30006
      - 30007:30007
      - 30008:30008
      - 30009:30009
    volumes:
      - ftp-app-data:/home/username/
      - ftp-conf-files:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: "$strTraefikDomains"
      FTP_USER_NAME: $username
      FTP_USER_PASS: $mypass
      FTP_USER_HOME: /home/username
    restart: always
    labels:
      io.rancher.container.hostname_override: container_name
      traefik.enable: true
      traefik.port: 30021
      traefik.backend.loadbalancer.stickiness: true
      traefik.backend.loadbalancer.method: drr
      traefik.backend.buffering.retryExpression: IsNetworkError() && Attempts() < 5
      traefik.frontend.rule: Host:$strTraefikDomains
      io.rancher.scheduler.affinity:host_label: ${host_label}
