version: '2'
services:
  phppgadmin:
    image: bitnami/phppgadmin
    stdin_open: true
    tty: true
    environment:
      DATABASE_HOST: $database_host
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: phppgadmin=true
      traefik.frontend.rule: Host:phppgadmin.apik.cloud
      traefik.enable: true
      traefik.port: '80'