version: '2'
services:
  phppgadmin:
    image: bitnami/phppgadmin
    stdin_open: true
    tty: true
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      DATABASE_HOST : $database_host
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: py3o=true
      traefik.frontend.rule: Host:phppgadmin.apik.cloud
      traefik.enable: true
      traefik.port: '80'