version: '2'
volumes:
  gitlab-app-data:
    driver: rancher-nfs
  gitlab-conf-files:
    driver: rancher-nfs
  gitlab-log-data:
    driver: rancher-nfs
services:
  gitlab-server:
    image: gitlab/gitlab-ce:9.5.10-ce.0
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.apik.cloud'
        registry_external_url 'http://registry.apik.cloud'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] =  $serveur_smtp
        gitlab_rails['smtp_port'] = $port_smtp
        gitlab_rails['smtp_user_name'] = $username_smtp
        gitlab_rails['smtp_password'] = $password_smtp
        gitlab_rails['smtp_domain'] = $domain_smtp
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['gitlab_email_from'] = $username_smtp
    volumes:
    - gitlab-app-data:/var/opt/gitlab
    - gitlab-log-data:/var/log/gitlab
    - gitlab-conf-files:/etc/gitlab
    ports:
    - 2222:22/tcp
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.hostname_override: container_name
      traefik.enable: true
      traefik.port: 80
      traefik.backend.loadbalancer.stickiness: true
      traefik.backend.loadbalancer.method: drr
      traefik.backend.buffering.retryExpression: IsNetworkError() && Attempts() < 5
      traefik.frontend.rule: Host:$strTraefikDomains
      io.rancher.scheduler.affinity:host_label: ${host_label}