version: '2'
catalog:
    name: "Gitlab"
    version: "1.0"
    description: "Gitlab by Apik"
    minimum_rancher_version: v1.3.2

    questions:
        -   variable: strTraefikDomains
            label: "Domaine Gitlab"
            required: true
            type: "string"
            default: "gitlab.apik.cloud"
             
            
            
            