version: '2'

catalog:
    name: "Apik Postgresql"
    version: "1.0"
    description: "Apik Postgresql"
    minimum_rancher_version: v1.3.2
    questions:
      - variable: strVersion
        label: "Postgres Version"
        description: "For eg. 12"
        type: "string"
        required: true
    
      - variable: strOdooPostgresVolumeName
        label: "Odoo Postgres Volume Name"
        type: "string"
        required: true
        default: "odoo_data_postgres"
      
      - variable: strOdooDataPostgres
        label: "Odoo Postgres Data"
        type: "string"
        required: true
        default: "/var/lib/postgresql/data/pgdata"

      - variable: strPgDB
        label: "Odoo Postgres DB"
        type: "string"
        required: true

      - variable: strPgPassword
        label: "Odoo Postgres Password"
        type: "string"
        required: true
      
      - variable: host_label
        label: "Node d'exécution"
        type: "string"
        required: true
        default: "pg_rancher=true"
        
      - variable: dedie_label
        label: "Si le serveur est dédié"
        type: "string"
        required: true
        default: "dedie=true"
      

services:
  postgres:
    start_on_create: true
