version: '2'

catalog:
    name: "Odoo Report API"
    version: "1.0"
    description: "Odoo Report API"
    minimum_rancher_version: v1.3.2
    questions:
      - variable: strVersion
        label: "Backend version"
        description: "For eg. 1.0"
        type: "string"
        required: true
        default: "latest"

      - variable: strApiUrl
        label: "API Url"
        type: "string"
        required: true

      - variable: strLogLevel
        label: "Log level"
        type: "string"
        required: true
        default: DEBUG

      - variable: "enumMode"
        label: "Mode"
        type: enum
        required: true
        options:
          - production
          - dev
        default: production

      - variable: boolResetMargin
        label: "Reset margins"
        type: "boolean"
        required: true
        default: false

      - variable: boolReportDebug
        label: "Debug mode for report"
        type: "boolean"
        required: true
        default: false

      - variable: boolWkhtmltopdfQt
        label: "Wkhtmltopdf QT (patched version)"
        type: "boolean"
        required: true
        default: false

      - variable: boolAutoClean
        label: "Auto clean reports after generated"
        type: "boolean"
        required: true
        default: true

      - variable: strReportDefaultName
        label: "Report default name"
        type: "string"
        required: true
        default: "report.pdf"

      - variable: strApiKey
        label: "API Key"
        type: "string"
        required: true

      - variable: intWorkers
        label: "Workers"
        type: "int"
        required: true
        default: 4

      - variable: strNodeExecution
        label: "Execution Node"
        type: "string"
        required: true
        default: "backend_api=true"

services:
  api:
    scale: 1
    start_on_create: true
