version: '2'

services:
  gitlab-server:
    image: gotenberg/gotenberg:7
    labels:
      traefik.enable: true
      traefik.port: 3000
      traefik.frontend.rule: Host:gotenberg.apik.cloud
      io.rancher.scheduler.affinity:host_label_ne: dedie=true