version: '2'

services:
  gitlab-server:
    image: thecodingmachine/gotenberg:6
    environment:
      # Database parameters
      DEFAULT_WAIT_TIMEOUT: 999999
      MAXIMUM_WAIT_TIMEOUT: 999999
      MAXIMUM_WAIT_DELAY: 999999
    labels:
      traefik.enable: true
      traefik.port: 3000
      traefik.frontend.rule: Host:gotenberg.apik.cloud
      io.rancher.scheduler.affinity:host_label_ne: dedie=true