version: '2'
services:

  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "crawler-db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${strMongoUser}
      MONGO_INITDB_ROOT_PASSWORD: ${strMongoPassword}
    labels:
      io.rancher.scheduler.affinity:host_label: ${strNodeExecution}

  master:
    image: crawlabteam/crawlab:latest
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_MONGO_PORT: "27017"
      CRAWLAB_MONGO_DB: "crawlab"
      CRAWLAB_MONGO_USERNAME: ${strMongoUser}
      CRAWLAB_MONGO_PASSWORD: ${strMongoPassword}
      CRAWLAB_MONGO_AUTHSOURCE: "admin"
    volumes:
      - "crawler-metadata:/root/.crawlab"
      - "crawler-data:/data"
      - "crawler-log:/var/logs/crawlab"
    ports:
      - "8080:8080"
      - "9666:9666"
    depends_on:
      - mongo
    labels:
      io.rancher.scheduler.affinity:host_label: ${strNodeExecution}
      traefik.enable: 'true'
      traefik.port: '8080'
      traefik.frontend.rule: Host:${strDomain}
      traefik.backend.buffering.retryExpression: IsNetworkError() && Attempts() < 5
      traefik.backend.loadbalancer.method: drr
      traefik.backend.loadbalancer.stickiness: 'true'

  worker01:
    image: crawlabteam/crawlab:latest
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_GRPC_ADDRESS: "master:9666"
      CRAWLAB_FS_FILER_URL: "http://master:8080/api/filer"
    volumes:
      - crawler-worker-01:/root/.crawlab
    depends_on:
      - master
    labels:
      io.rancher.scheduler.affinity:host_label: ${strNodeExecution}

  worker02:
    image: crawlabteam/crawlab:latest
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_GRPC_ADDRESS: "master:9666"
      CRAWLAB_FS_FILER_URL: "http://master:8080/api/filer"
    volumes:
      - crawler-worker-02:/root/.crawlab
    depends_on:
      - master
    labels:
      io.rancher.scheduler.affinity:host_label: ${strNodeExecution}

volumes:
  crawler-db:
    driver: rancher-nfs
    external: true
  crawler-metadata:
    driver: rancher-nfs
    external: true
  crawler-log:
    driver: rancher-nfs
    external: true
  crawler-data:
    driver: rancher-nfs
    external: true
  crawler-worker-01:
    driver: rancher-nfs
    external: true
  crawler-worker-02:
    driver: rancher-nfs
    external: true

