version: '2'

catalog:
    name: "ApiX Web Crawler"
    version: "1.0"
    description: "ApiX Backend API"
    minimum_rancher_version: v1.3.2
    questions:
      - variable: strDomain
        label: "Crawler Domain"
        type: "string"
        required: true

      - variable: strMongoUser
        label: "Mongo User"
        description: "For eg. admin"
        type: "string"
        required: true
        default: "admin"

      - variable: strMongoPassword
        label: "Mongo Password"
        description: "For eg. admin"
        type: "string"
        required: true

      - variable: strNodeExecution
        label: "Execution Node"
        type: "string"
        required: true
        default: "crawler=true"


services:
  mongo:
    scale: 1
    start_on_create: true
  master:
    scale: 1
    start_on_create: true
  worker01:
    scale: 1
    start_on_create: true
  worker02:
    scale: 1
    start_on_create: true

