version: '2'
services:
  maildev:
    image: maildev/maildev
    
    labels:
        io.rancher.container.hostname_override: container_name
        io.rancher.scheduler.affinity:host_label: maildev=true
        traefik.frontend.rule: Host:maildev.apik.cloud
        traefik.enable: true
        traefik.port: '80'